# NeonDB PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://ep-mute-cell-ahksssaf.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_L1ecnWH2mJQT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Init database
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Security secret properties (minimum 256 bits for HS256 JWT key)
jwt.secret=9a6117b489be42fb4864197e44a7f050fd7af53e2069fae7ee61327150a006ee
jwt.expiration-ms=86400000

# Server port definition
server.port=8080
