# NeonDB PostgreSQL datasource configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-mute-cell-ahksssaf.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_L1ecnWH2mJQT}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# Init database
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Security secret properties
jwt.secret=${JWT_SECRET:9a6117b489be42fb4864197e44a7f050fd7af53e2069fae7ee61327150a006ee}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}

# Security CORS Configuration
cors.allowed.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:8080}

# Server port definition
server.port=${PORT:8080}
